service: util

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage}
  region: eu-west-1
  cfLogs: true
  stackTags:
    budgetCode: "81137"
  deploymentBucket: ${self:provider.stage}-deployment.ri-tech.io

package:
  individually: true

custom: ${file(./config/${self:provider.stage}-config.yml)}

functions:
  calculateGeo:
    name: ${self:provider.stage}-${self:service}-calculateGeo
    description: Uses APEX and Serverless
    handler: index.handle
    memorySize: ${self:custom.memorySize}
    timeout: ${self:custom.timeout}
    package:
      artifact: apex/calculateGeo.zip
    events:
      - http:
          path: ${self:custom.majorVersion}/geo/calculate
          method: POST
      - http:
          path: ${self:custom.majorVersion}/geo/calculate/{postcode}
          method: GET